x-volumes:
  - &project-volume ../apps:/project/apps
  - &app-volume ../apps/app:/app
  - &api-volume ../apps/api:/app

services:

  cli:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cli
      # cache_from: ['type=gha,scope=jrsouth/github-action-tests/v1']
      # cache_to: ['type=gha,scope=jrsouth/github-action-tests/v1,mode=max']
      cache_from: ['type=local,src=./cache']
      cache_to: ['type=local,dest=./cache,mode=max']
    tty: true
    volumes:
      - *project-volume


  # app:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile.app
  #     cache_from: ['type=gha']
  #     cache_to: ['type=gha,mode=max']
  #   image: ${GOOGLE_DOCKER_REPOSITORY:-library}/${COMPOSE_PROJECT_NAME}-app:${NEW_RELEASE_VERSION:-latest}
  #   volumes:
  #     - *app-volume
  #   ports:
  #     - 3100:3000


  # api:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile.api
  #     cache_from: ['type=gha']
  #     cache_to: ['type=gha,mode=max']
  #   image: ${GOOGLE_DOCKER_REPOSITORY:-library}/${COMPOSE_PROJECT_NAME}-api:${NEW_RELEASE_VERSION:-latest}
  #   volumes:
  #     - *api-volume
