x-volumes:
  - &project-volume ../apps:/project/apps
  - &app-volume ../apps/app:/app
  - &api-volume ../apps/api:/app

services:

  cli:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cli
      cache_from: ['type=local,src=./cache/cli']
      cache_to: ['type=local,dest=./cache/cli,mode=max']
    tty: true
    volumes:
      - *project-volume


  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
      cache_from: ['type=local,src=./cache/app']
      cache_to: ['type=local,dest=./cache/app,mode=max']
    image: ${GOOGLE_DOCKER_REPOSITORY:-library}/${COMPOSE_PROJECT_NAME}-app:${NEW_RELEASE_VERSION:-latest}
    volumes:
      - *app-volume
    ports:
      - 3100:3000


  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
      cache_from: ['type=local,src=./cache/api']
      cache_to: ['type=local,dest=./cache/api,mode=max']
    image: ${GOOGLE_DOCKER_REPOSITORY:-library}/${COMPOSE_PROJECT_NAME}-api:${NEW_RELEASE_VERSION:-latest}
    volumes:
      - *api-volume
