x-volumes:
  - &project-volume ../apps:/project/apps
  - &app-volume ../apps/app:/app
  - &api-volume ../apps/api:/app

services:

  cli:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cli
    tty: true
    volumes:
      - *project-volume



  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    image: ${GOOGLE_DOCKER_REPOSITORY:-library}/${COMPOSE_PROJECT_NAME}-app:${NEW_RELEASE_VERSION:-latest}
    labels:
      production: true
    volumes:
      - *app-volume
    ports:
      - 3100:3000

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    # image: ${DOCKER_REPOSITORY:-local}/${PROJECT_NAME:-artifact-registry-test}-api
    volumes:
      - *api-volume
