name: Build and push containers to GAR
run-name:
on:
  push:
    branches:
      - main
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - 'main'
env:
  GH_TOKEN: ${{ github.token }}

jobs:

  # We need a release version for our container tags
  create-release:
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create the new release's version
        id: create-release-tag
        run: |
          CURRENT_RELEASE_VERSION=$(gh release list --json tagName --jq '.[].tagName' | sed -e 's/^v//' | sort -hrt '.' -k 1,1 -k 2,2 -k 3,3 | head -n 1)
          echo "Current release: " $CURRENT_RELEASE_VERSION
          NEW_RELEASE_VERSION=$(awk -F '.' '{print $1 "." $2 "." $3 + 1}' <<< $CURRENT_RELEASE_VERSION)
          echo "New release: " $NEW_RELEASE_VERSION
          echo "NEW_RELEASE_VERSION=$NEW_RELEASE_VERSION" >> "$GITHUB_OUTPUT"
          echo "Prepared new release $NEW_RELEASE_VERSION" >> "$GITHUB_STEP_SUMMARY"

      - name: Create a GitHub release
        env:
          NEW_RELEASE_VERSION: ${{ steps.create-release-tag.outputs.NEW_RELEASE_VERSION }}
        run: |
          RELEASE_BRANCH=$(git branch --show-current)
          [[ "$RELEASE_BRANCH" = "main" ]] && RELEASE_TYPE_FLAG="--latest" || RELEASE_TYPE_FLAG="--prerelease"
          [[ "$RELEASE_BRANCH" = "main" ]] || RELEASE_TITLE_SUFFIX="on $RELEASE_BRANCH"
          gh release create "v$NEW_RELEASE_VERSION" \
            --generate-notes \
            --target $RELEASE_BRANCH
            --title "Release $NEW_RELEASE_VERSION$RELEASE_TITLE_SUFFIX" \
            $RELEASE_TYPE_FLAG


  # build-containers:
  #   # if: github.event.pull_request.merged == true
  #   needs: create-release
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'
  #   steps:

  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Build images
  #       run: docker compose -f docker/docker-compose.yml build


  # push-to-gar:
  #   needs: build-containers
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'
  #   steps:

  #     - name: Configure Google authentication
  #       id: 'auth'
  #       uses: 'google-github-actions/auth@v2'
  #       with:
  #         project_id: burnished-edge-427513-m7
  #         workload_identity_provider: projects/941946528420/locations/global/workloadIdentityPools/github/providers/github-repo-provider

  #     - name: 'Set up Cloud SDK'
  #       uses: 'google-github-actions/setup-gcloud@v2'
  #       with:
  #         version: '>= 363.0.0'

  #     - name: Test gcloud auth connection
  #       run: gcloud config configurations list


  #   # - name: Push images
  #   #   run: docker compose -f docker/docker-compose.yml push


  #   # - id: 'auth'
  #   #   uses: 'google-github-actions/auth@v2'
  #   #   with:
  #   #     workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
  #   #     service_account: 'github-actions@burnished-edge-427513-m7.iam.gserviceaccount.com'

  #   # - name: 'Set up Cloud SDK'
  #   #   uses: 'google-github-actions/setup-gcloud@v2'
  #   #   with:
  #   #     version: '>= 363.0.0'

  #   # - name: 'Use gcloud CLI'
  #   #   run: 'gcloud info'
