name: build-all-containers
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - 'main'

jobs:
  build-containers:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'


    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Where am I?
      run: pwd

    - name: What have I got?
      run: ls -lash

    - name: Build images
      run: docker compose -p art-reg -f docker/docker-compose.yml build


    # - id: 'auth'
    #   uses: 'google-github-actions/auth@v2'
    #   with:
    #     workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
    #     service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

    # - name: 'Set up Cloud SDK'
    #   uses: 'google-github-actions/setup-gcloud@v2'
    #   with:
    #     version: '>= 363.0.0'

    # - name: 'Use gcloud CLI'
    #   run: 'gcloud info'
