name: Build and push containers to GAR
run-name:
on:
  push:
    branches:
      - main
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - 'main'
env:
  GH_TOKEN: ${{ github.token }}
  PROJECT_NAME: 'art-registry'

jobs:

  create-release:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
      contents: write
      id-token: 'write'

    steps:


      # Get the code

      - name: Checkout the code
        uses: actions/checkout@v4

      # Configure and test our Google credentials
      # See: [xxx todo: dig out the link]

      - name: Configure Google authentication
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Test gcloud auth connection
        run: gcloud config configurations list

      - name: Configure Docker authentication for the Google Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GOOGLE_DOCKER_REGISTRY}} --quiet


      # Now the work begins

      - name: Create the new release's version number
        id: create-release-tag
        run: |
          CURRENT_RELEASE_VERSION=$(gh release list --json tagName --jq '.[].tagName' | sed -e 's/^v//' | sort -hrt '.' -k 1,1 -k 2,2 -k 3,3 | head -n 1)
          echo "Current release: " $CURRENT_RELEASE_VERSION
          NEW_RELEASE_VERSION=$(awk -F '.' '{print $1 "." $2 "." $3 + 1}' <<< $CURRENT_RELEASE_VERSION)
          echo "New release: " $NEW_RELEASE_VERSION
          echo "NEW_RELEASE_VERSION=$NEW_RELEASE_VERSION" >> "$GITHUB_OUTPUT"
          echo "Prepared new release $NEW_RELEASE_VERSION" >> "$GITHUB_STEP_SUMMARY"

      - name: Build the docker images
        run: docker compose -p $PROJECT_NAME -f docker/docker-compose.yml build

      # - name: Tag the docker images # (Might need native docker not compose...)
      #   env:
      #     NEW_RELEASE_VERSION: ${{ steps.create-release-tag.outputs.NEW_RELEASE_VERSION }}
      #   run: docker compose -p $PROJECT_NAME -f docker/docker-compose.yml tag

      - name: Push the docker images
        run: docker compose -p $PROJECT_NAME -f docker/docker-compose.yml push

      # We do the GitHub release only after a successful build/push, otherwise
      # we'll have a GitHub release without any corresponding Google Artifact
      # Repository images - which in a very practical way isn't a real release.
      - name: Create a GitHub release
        env:
          NEW_RELEASE_VERSION: ${{ steps.create-release-tag.outputs.NEW_RELEASE_VERSION }}
        run: |
          RELEASE_BRANCH=$(git branch --show-current)
          [[ "$RELEASE_BRANCH" = "main" ]] && RELEASE_TYPE_FLAG="--latest" || RELEASE_TYPE_FLAG="--prerelease"
          [[ "$RELEASE_BRANCH" = "main" ]] || RELEASE_TITLE_SUFFIX="on $RELEASE_BRANCH"
          gh release create "v$NEW_RELEASE_VERSION" \
            --generate-notes \
            --target $RELEASE_BRANCH \
            --title "Release v$NEW_RELEASE_VERSION$RELEASE_TITLE_SUFFIX" \
            $RELEASE_TYPE_FLAG
