name: Build and push containers to GAR
run-name:
on:
  push:
    branches:
      - main
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - 'main'

jobs:

  # We need a release version for our container tags
  create-release:
    id: create-release
    runs-on: ubuntu-24.04
    steps:
      - name: Populate new release tag
        run: |
          echo 'NEW_RELEASE_TAG=1.2.3' >> "$GITHUB_OUTPUT"
          echo 'First sentence' >> "$GITHUB_STEP_SUMMARY"
          echo '' >> "$GITHUB_STEP_SUMMARY"
          echo '# A heading?' >> "$GITHUB_STEP_SUMMARY"
          echo '- Bullet with `code` :nerd-face:' >> "$GITHUB_STEP_SUMMARY"


      - name: Collect new release tag
        env:
          NEW_RELEASE_TAG: ${{ steps.create-release.outputs.NEW_RELEASE_TAG }}
        run: echo 'NEW_RELEASE_TAG is ' $NEW_RELEASE_TAG


  # build-containers:
  #   # if: github.event.pull_request.merged == true
  #   needs: create-release
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'
  #   steps:

  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Build images
  #       run: docker compose -f docker/docker-compose.yml build


  # push-to-gar:
  #   needs: build-containers
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'
  #   steps:

  #     - name: Configure Google authentication
  #       id: 'auth'
  #       uses: 'google-github-actions/auth@v2'
  #       with:
  #         project_id: burnished-edge-427513-m7
  #         workload_identity_provider: projects/941946528420/locations/global/workloadIdentityPools/github/providers/github-repo-provider

  #     - name: 'Set up Cloud SDK'
  #       uses: 'google-github-actions/setup-gcloud@v2'
  #       with:
  #         version: '>= 363.0.0'

  #     - name: Test gcloud auth connection
  #       run: gcloud config configurations list


  #   # - name: Push images
  #   #   run: docker compose -f docker/docker-compose.yml push


  #   # - id: 'auth'
  #   #   uses: 'google-github-actions/auth@v2'
  #   #   with:
  #   #     workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
  #   #     service_account: 'github-actions@burnished-edge-427513-m7.iam.gserviceaccount.com'

  #   # - name: 'Set up Cloud SDK'
  #   #   uses: 'google-github-actions/setup-gcloud@v2'
  #   #   with:
  #   #     version: '>= 363.0.0'

  #   # - name: 'Use gcloud CLI'
  #   #   run: 'gcloud info'
